<? $config = include APP_DIR . 'config/constants.php'?>
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js">
	<!--<![endif]-->
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
		<title></title>
		<meta name="description" content="">
		<meta name="viewport" content="width=device-width">

		<link rel="stylesheet" href="<?= $config->application->baseUri?>css/bootstrap.min.css">
		<style>
			body {
				padding-top: 50px;
				padding-bottom: 20px;
			}
		</style>
		<link rel="stylesheet" href="<?= $config->application->baseUri?>css/bootstrap-theme.min.css">
		<link rel="stylesheet" href="<?= $config->application->baseUri?>css/main.css">

		<script src="<?= $config->application->baseUri?>js/vendor/modernizr-2.6.2-respond-1.1.0.min.js"></script>
		<!--<script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.1/jquery.min.js"></script>-->
		<script src="<?= $config->application->baseUri?>js/vendor/jquery-1.10.1.min.js"></script>
		<script src="<?= $config->application->baseUri?>js/vendor/bootstrap.min.js"></script>
		<script src="<?= $config->application->baseUri?>js/angular.min.js"></script>
		<script src="<?= $config->application->baseUri?>js/main.js"></script>
	</head>
	<body>
		<!--[if lt IE 7]>
		<p class="chromeframe">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">activate Google Chrome Frame</a> to improve your experience.</p>
		<![endif]-->
		<div class="navbar navbar-inverse navbar-fixed-top">
			<div class="container">
				<div class="navbar-header">
					<a class="navbar-brand" href="/">RESTFul API</a>
				</div>
				<div class="navbar-collapse collapse">
					<ul class="nav navbar-nav">
						<li <?= strpos($_SERVER['REQUEST_URI'], '/galeria') !== false ? 'class="active"' : ''?>>
							<a href="/galeria">GALERIA</a>
						</li>
						<li <?= strpos($_SERVER['REQUEST_URI'], '/user') !== false ? 'class="active"' : ''?>>
							<a href="/user/get">USER</a>
						</li>
					</ul>
				</div>
			</div>
		</div>
		
		<div class="env" style="text-align:center;">
			<div class="container" style="display:inline-block; text-align:left;">
			<?php echo $this->getContent(); ?>
			</div>
		</div>
		
		<footer>
			<p style="text-align: center;">
				developed by nancorrea - divea.com.br
			</p>
		</footer>
	</body>
</html>