<style>
	.table{
		font-size:12px;
		width:900px;
	}
	.table th{
		padding:8px 0 !important;
	}
	.table tr:hover td{
		background:#B9DEF0;
		cursor:pointer;
	}
</style>
<script>
	$(function() {
		$.ajax({
			url: 'http://<?= $_SERVER['HTTP_HOST']?>/api/crud/user',
			type: 'GET',
			complete: function(request, json) {
				try{
					array = JSON.parse(request.responseText);
					$(array).each(function(e){
						$('.pool table').append('\
							<tr data-ai="'+array[e].cd_user+'">\
								<td>'+array[e].cd_user+'</td>\
								<td>'+array[e].nm_user+'</td>\
								<td>'+array[e].em_user+'</td>\
								<td>'+array[e].role+'</td>\
								<td>'+array[e].username+'</td>\
							</tr>\
						');
					});
				} catch( err ) {
	                console.log(err);
	            }
			}
		});
		
		$('.table').delegate('tr','click',function(){
			if($(this).data('ai')) {
				$('.pool').slideUp(function() {
					$('#requestForm').slideDown();
				});
				$('.uri').val('http://<?= $_SERVER['HTTP_HOST']?>/api/crud/user/'+$(this).data('ai'));
			} 
		});
		
		$('#requestForm').submit(function() {
			$.ajax({
				url: $('.uri').val(),
				type: 'DELETE',
				data: $('#requestForm').serialize(),
				complete: function(request, json) {
					$('.response pre').html(request.responseText);		
				}
			});
			return false;
		});
	});
</script>

<div class="jumbotron">
	<div class="container">
		<div class="row">
			<a href="/user/get" class="btn btn-warning">GET</a>
			<a href="/user/post" class="btn btn-success">POST</a>
			<a href="/user/put" class="btn btn-info">PUT</a>
			<a href="/user/delete" class="btn btn-danger">DELETE</a>
			<br><br>
			
			
			<h2>DELETE</h2>
			<div class="pool">
				<table class="table" align=center>
					<tr>
						<th>ID: </th>
						<th>Nome: </th>
						<th>Email: </th>
						<th>Papel: </th>
						<th>Usuário: </th>
					</tr>
				</table>
			</div>
		</div>
		
		<form id="requestForm" style="display:none">
		<div class="row">
			<small>delete record</small>
			<div class="form-group">
				<input type="text" readonly="readonly" class="form-control uri" value="http://<?= $_SERVER['HTTP_HOST']?>/api/crud/user">
				<button type="submit" class="btn btn-success">DO HTTP REQUEST</button>
			</div>
		</div>
		<div class="row response">
			<h3>Response:</h3>
			<pre style="width:900px;">[]</pre>	
		</div>
		</form>
	</div>
</div>	

