<script>
	var single_request = false; 
	$(function() {
		$('#requestForm').delegate('.btn-info','click',function(){
			$('.uri').val('http://<?= $_SERVER['HTTP_HOST']?>/api/crud/user/'+$(this).data('id'));
			$('#requestForm').submit();
		});
		$('#requestForm').delegate('.btn-success','click',function(){
			$('.uri').val('http://<?= $_SERVER['HTTP_HOST']?>/api/crud/user');
			$('.btn-info').remove();
			$('#requestForm').submit();
		});

		//submit forms		
		$('#requestForm').submit(function() {
			$.ajax({
				url: $('.uri').val(),
				type: 'GET',
				complete: function(request, json) {
					
					//outputs response
					$('.response pre').html(request.responseText);		
					try{
						//parses response as JSON;
						array = JSON.parse(request.responseText);
						//takes first object attribute as its ID for single request;
						$('.form-group').append('<button type="button" data-id="'+array[0][Object.keys(array[0])[0]]+'" class="btn btn-info">GET FIRST RESULT</button>');
					
					} catch( err ) {
		                console.log(err);
		            }
				}
			});
			return false;
		});
	});
</script>

<div class="jumbotron">
	<div class="container">
		<div class="row">
			<h2>GET</h2>
			<small>retrieving data</small>
			<form id="requestForm">
			<div class="form-group">
				<input type="text" readonly="readonly" class="form-control uri" value="http://<?= $_SERVER['HTTP_HOST']?>/api/crud/user">
				<button type="button" class="btn btn-success">DO HTTP REQUEST</button>
			</div>
		</form>
		</div>
		<div class="row response">
			<h3>Response:</h3>
			<pre style="width:900px;">[]</pre>	
		</div>
	</div>
</div>	

