<script>
	var single_request = false;
	
	$(function() {
		//submit forms		
		$('#requestForm').submit(function() {
			
			$(this).doPost('/api/crud/galeria', function(){
				
				$('.response pre').html(request.responseText);
				
			});
			
			return false;
		});
		
		$("#photo").change(function(e){
 			$(this).prepareSend(e);
		});
	});
	
	
</script>

<div class="jumbotron">
	<div class="container">
		<form id="requestForm">
		<div class="row">
			<h2>POST</h2>
			
			<div class="input-group input-group-sm">
			  <input type="text" class="form-control" name="nm_galeria" placeholder="name">
			</div>
			<div class="input-group input-group-sm">
			  <input type="file" class="form-control" name="photo" placeholder="photo" id="photo">
			</div>
			
			<div class="form-group">
				<input type="text" readonly="readonly" class="form-control uri" value="http://<?= $_SERVER['HTTP_HOST']?>/api/crud/user">
				<button type="submit" class="btn btn-success">DO HTTP REQUEST</button>
			</div>
		</div>
		</form>
		<div class="row response">
			<h3>Response:</h3>
			<pre style="width:900px;">[]</pre>	
		</div>
	</div>
</div>	

