<script>
	var userModule = angular.module('myApp',[]);
	
	userModule.service('crudService', function( $rootScope, $http ) {
	    
	    this.list = function( apiUri ) {
	        return $http.get(apiUri);
	    }
	    
	    /*this.save = function(obj, apiUri) {
	        post = $http({
	           method: 'POST',
	           url: apiUri,
	           data: $.param(obj)
	        });
	        post.success(function ( response ) 
	        {
	            $rootScope.message = response.message;
	            if( response.status != 'success' ) {
	                $rootScope.result = false;
	            }
	        });
	        return $rootScope.result !== false ? post : false; 
	    }*/
	});
	
	userModule.controller('userController', function( $rootScope, $scope, $http, crudService ) {
	    
	    $scope.apiUri = '/api/crud/user';
	    $scope.users = [{}];
	    
	    $scope.readFile = function() 
	    {
            fileReader.readAsDataUrl($scope.file, $scope).then(function( result ){
               $scope.imageSrc = result; 
            });
	    }
	    
	    $scope.list = function() 
	    {
            crudService.list($scope.apiUri).then(function ( response ) {
                $scope.users = response.data
            });
	    }
	    
	    /*$scope.postForm = function() 
	    {
	        if( save = crudService.save($scope.newUser, $scope.apiUri) ) {
	            save.then(function ( response ) {

                    $rootScope.response = response;
                   
                    if ( ! $scope.users instanceof Array ) this.list();                    
                    $scope.users.push(response.data.data[0]);
                });
	        }
	    }*/
	    
	    
	});
	
	
	
	(function($){
        $.base64encode = function(value,callback) 
        {
            var reader = new FileReader();
            reader.onload = callback;
            reader.readAsDataURL(value);
        },
        $.fn.prepareSend = function(e,angularController) 
        {
            element = $(this);
            if( true
                element.data('limit') == 'n' ||
                element.parents('form').find('input[name=\'image[]\']').length < element.data('limit')
            ) {
                $.base64encode(e.target.files[0], function(e){
                    
                    img = e.target.result;
                    
                    angular.element(angularController).scope().addImage(img);
                    
                    if($('.imagesUploaded').length > 0) {
                        $('.imagesUploaded').append('<img src="'+img+'"/>');    
                    }
                    
                    element.val('');
                });
            }
        }
    }) ( jQuery );



	$(function() {
        $("#photo").change(function(e){
            $(this).prepareSend(e,'#userController');
        });
    });
	
	
</script>





<div class="jumbotron">
	<div class="container">
		
		
		<div class="row" id="userController" ng-controller="userController" ng-init="list()">
			<div id="messages" ng-show="message">{{ message }}</div>
           
			
			
			<h2>POST</h2>
			
			
			<form ng-submit="postForm()" id="postForm">
			    <div class="input-group input-group-sm">
                    <input type="file" class="form-control" ng-change="change()" ng-model="newUser.images" id="photo" data-limit="1">
                </div>
                
                <img ng-src="{{ image }}"/>
                
    			<div class="input-group input-group-sm">
                    <input type="text" class="form-control" ng-model="newUser.nm_user" placeholder="name">
                </div>
                <div class="input-group input-group-sm">
                    <input type="text" class="form-control" ng-model="newUser.em_user" placeholder="email">
                </div>
                <div class="input-group input-group-sm">
                    <input type="text" class="form-control" ng-model="newUser.username" placeholder="username">
                </div>
                <div class="form-group">
                    <button type="submit" class="btn btn-success">DO HTTP REQUEST</button>
                </div>
            </form>
            
			
			<small>data preview</small>
			<pre>{{ image }}</pre>
	        <pre style="width:900px;">{{ response.data }}</pre>  
	        
            <img ng-src="{{imageSrc}}"/>
            
		    <table>
		        <tr ng-repeat="user in users">
		            <td>{{ user.nm_user }}</td>
		        </tr>
		    </table>
		</div>
		
	</div>
</div>	

