<style>
	.table{
		font-size:12px;
		width:900px;
	}
	.table th{
		padding:8px 0 !important;
	}
	.table tr:hover td{
		background:#B9DEF0;
		cursor:pointer;
	}
</style>
<script>
	$(function() {
		$.ajax({
			url: 'http://<?= $_SERVER['HTTP_HOST']?>/api/crud/user',
			type: 'GET',
			complete: function(request, json) {
				try{
					array = JSON.parse(request.responseText);
					$(array).each(function(e){
						$('.pool table').append('\
							<tr data-ai="'+array[e].cd_user+'">\
								<td>'+array[e].cd_user+'</td>\
								<td>'+array[e].nm_user+'</td>\
								<td>'+array[e].em_user+'</td>\
								<td>'+array[e].role+'</td>\
								<td>'+array[e].username+'</td>\
							</tr>\
						');
					});
				} catch( err ) {
	                console.log(err);
	            }
			}
		});
		
		$('.table').delegate('tr','click',function(){
			if($(this).data('ai')) {
				$('.pool').slideUp(function() {
					$('#requestForm').slideDown();
				});
				$.ajax({
					url: 'http://<?= $_SERVER['HTTP_HOST']?>/api/crud/user/'+$(this).data('ai'),
					type: 'GET',
					complete: function(request, json) {
						try{
							array = JSON.parse(request.responseText);
							
							$('input[name=nm_user]').val(array.nm_user);
							$('input[name=em_user]').val(array.em_user);
							$('input[name=role]').val(array.role);
							$('input[name=username]').val(array.username);
							$('input[name=password]').val(array.password);
									
						} catch( err ) {
			                console.log(err);
			            }
					}
				});
				$('.uri').val('http://<?= $_SERVER['HTTP_HOST']?>/api/crud/user/'+$(this).data('ai'));
			} 
		});
		
		$('#requestForm').submit(function() {
			$.ajax({
				url: $('.uri').val(),
				type: 'PUT',
				data: $('#requestForm').serialize(),
				complete: function(request, json) {
					$('.response pre').html(request.responseText);		
				}
			});
			return false;
		});
	});
</script>

<div class="jumbotron">
	<div class="container">
		<div class="row">
			<h2>PUT</h2>
			
			<div class="pool">
				<table class="table" align=center>
					<tr>
						<th>ID: </th>
						<th>Nome: </th>
						<th>Email: </th>
						<th>Papel: </th>
						<th>Usuário: </th>
					</tr>
				</table>
			</div>
		</div>
		
		<form id="requestForm" style="display:none">
		<div class="row">
			<div class="input-group input-group-sm">
			  <input type="text" class="form-control" name="nm_user" placeholder="name">
			</div>
			<div class="input-group input-group-sm">
			  <input type="text" class="form-control" name="em_user" placeholder="email">
			</div>
			<div class="input-group input-group-sm">
			  <select class="form-control" name="role" placeholder="role">
			  		<option value="">role</option>
			  		<option>admin</option>
			  		<option>moderator</option>
			  		<option>user</option>
			  </select>
			</div>
			<div class="input-group input-group-sm">
			  <input type="text" class="form-control" name="username" placeholder="username">
			</div>
			<div class="input-group input-group-sm">
			  <input type="text" class="form-control" name="password" placeholder="password">
			</div>
			
			<small>update record</small>
			<div class="form-group">
				<input type="text" readonly="readonly" class="form-control uri" value="http://<?= $_SERVER['HTTP_HOST']?>/api/crud/user">
				<button type="submit" class="btn btn-success">DO HTTP REQUEST</button>
			</div>
		</div>
		<div class="row response">
			<h3>Response:</h3>
			<pre style="width:900px;">[]</pre>	
		</div>
		</form>
	</div>
</div>	

